---
- hosts: kubernetes

  vars:
    - kubemanpw: Welcome@2021

  tasks:
    - name: update 
      yum:
        name: '*'
        state: latest

    - name: install podman
      yum:
        name: podman
        state: present

    - name: install kvm hypervisor
      #command: yum -y install "@virt"
      yum:
        name: '@Virtualization Host'
        state: present

    - name: install more kvm stuff
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - libguestfs-tools
        - virt-manager

    - name: ensure sock group is set
      lineinfile:
        path: /etc/libvirt/libvirtd.conf
        regexp: '^unix_sock_group'
        line: 'unix_sock_group = "libvirt"'
    - name: ensure sock rw is set
      lineinfile:
        path: /etc/libvirt/libvirtd.conf
        regexp: '^unix_sock_rw_perms'
        line: 'unix_sock_rw_perms = "0770"'

    - name: ensure passwordless sudo for group libvirt
      copy:
        dest: /etc/sudoers.d/libvirt
        content: |
          %libvirt ALL=(ALL) NOPASSWD: ALL

    - name: start and enable libvirtd
      service:
        name: libvirtd
        state: started
        enabled: yes

    - name: download kubectl
        #curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/v1.22.2/bin/linux/amd64/kubectl
        dest: /usr/local/bin
        mode: 0755

    - name: install minikube
#        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: 0755

    - name: disable swap
      command: swapoff -a
    - name: disable swap fstab
      lineinfile:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        line: '# \1'

    - name: ensure groups for user kubeman
      group:
        name: kubeman
        state: present
    - name: add user kubeman
      user:
        name: kubeman
        groups: "{{ item }}"
        append: yes
        password: "{{ kubemanpw|password_hash('sha512') }}"
      loop:
        - wheel
        - libvirt
        - kubeman
...
